### ISSUE TITLE
麻烦问下注册不了怎么办（不会也不想学魔法的话）

### ISSUE THREAD

**Issue by lmflmz** [viva-la-vita/viva-la-vita.github.io#2]
[问题图片.zip](https://github.com/viva-la-vita/viva-la-vita.github.io/files/13715963/default.zip)

**Comment by tansongchen** [comment]
目前邮件发送功能已经恢复正常，如果仍无法注册，可以重新开启本 issue。另外，这个仓库是关于主页的，论坛相关问题可以在 https://github.com/viva-la-vita/bbs 提出。
